# Generated by Django 5.0 on 2023-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authaccounts', '0002_useraccount_aboutmovielife_useraccount_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'others')], default='O', max_length=255, null=True),
        ),
    ]
