# Generated by Django 5.0 on 2023-12-27 04:50

import authaccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authaccounts', '0004_useraccount_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='profile_images/defaultprofile.png', upload_to=authaccounts.models.upload_to, verbose_name='Image'),
        ),
    ]
