# Generated by Django 5.0 on 2023-12-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(default='Hindi', on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='movies.language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(default='Youtube', on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='movies.platform'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_link',
            field=models.TextField(),
        ),
    ]
