# Generated by Django 5.0 on 2023-12-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_language_alter_movie_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_name',
            field=models.CharField(default='hindi', max_length=255),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='movies.platform'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_name',
            field=models.CharField(default='Youtube', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.ManyToManyField(to='movies.language'),
        ),
    ]
