# Generated by Django 5.0 on 2023-12-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_language_lang_name_remove_movie_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='platform_name',
            new_name='name',
        ),
    ]
