# Generated by Django 5.0 on 2023-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_lang_name_language_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.AlterField(
            model_name='movie',
            name='platform',
            field=models.CharField(default='Youtube', max_length=255),
        ),
        migrations.DeleteModel(
            name='language',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Hindi', max_length=255),
        ),
        migrations.DeleteModel(
            name='platform',
        ),
    ]
