# Generated by Django 5.0 on 2023-12-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_director_movie_duration_movie_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewfromweb',
            name='made_at',
            field=models.DateField(),
        ),
    ]
