# Generated by Django 5.0 on 2023-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_storyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platform_link',
            field=models.CharField(default='Youtube', max_length=255),
        ),
    ]
