# Generated by Django 4.2.6 on 2024-01-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_favouritemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfromweb',
            name='userProfile',
            field=models.TextField(default='http://arshdeep54.pythonanywhere.com/media/profile_images/defaultprofile.png'),
        ),
    ]
