# Generated by Django 4.2.6 on 2024-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_reviewfromweb_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='userProfile',
            field=models.TextField(default='http://arshdeep54.pythonanywhere.com/media/profile_images/defaultprofile.png'),
        ),
        migrations.AddField(
            model_name='reviewfromweb',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewfromweb',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
