# Generated by Django 4.2.6 on 2024-01-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='userProfile',
            field=models.TextField(default='http://arshdeep54.pythonanywhere.com/media/profile_images/defaultprofile.png'),
        ),
    ]
